services:
  db:
    image: postgres:17
    restart: always
    env_file: .env
    ports:
      - '5432:5432' 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
